name: 🏷️ Publish NPM (version prompt)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Fixed Version'
        required: true
        type: string
      tag:
        type: choice
        description: Tag
        options:
          - latest
          - beta

permissions:
  contents: write
  id-token: write

jobs:
  deploy-npm-prompt:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Retrieve current Date Time in EST
        shell: bash
        run: echo "START_TIME=$(TZ=":America/New_York" date -R|sed 's/.....$//')" >> $GITHUB_ENV

      - name: Current datetime - ${{ env.START_TIME }}
        run: echo ${{ env.START_TIME }}

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.event.pull_request.merged != true && contains('["ghiscoding"]', github.actor) != true }}
        name: Exit early when current actor is not allowed to push new release
        run: |
          echo "Error: Your GitHub username (${{ github.actor }}) is not on the allowed list of admins for this workflow"
          exit 1

      - name: Set NodeJS
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Run pnpm install dependencies
        run: pnpm install

      - name: Run all workspace TSC builds
        run: pnpm build:full

      - name: Lerna Version (latest) 🏷️
        if: ${{ contains(inputs.tag, 'latest') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          pnpm whoami
          pnpm run local-lerna version ${{ inputs.version }} --yes

      - name: Lerna Version (beta) 🏷️
        if: ${{ contains(inputs.tag, 'beta') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          pnpm whoami
          pnpm run local-lerna version prerelease --conventional-commits --conventional-prerelease --preid beta --force-publish --yes

      - name: OTP
        if: ${{ inputs.dryrun != true }}
        uses: step-security/wait-for-secrets@v1
        id: wait-for-secrets
        with:
          secrets: |
            OTP:
              name: 'OTP to publish package'
              description: 'OTP from authenticator app'

      - name: Lerna Publish 📦
        if: ${{ inputs.dryrun != true }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        id: lerna-publish
        run: |
          # Attempt to publish all packages
          pnpm run local-lerna publish from-package --force-publish --yes --otp ${{ steps.wait-for-secrets.outputs.OTP }}
          EXIT_CODE=$?
          echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV
          OUTPUT=$(cat /dev/stdout)
          echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV
          if [ $EXIT_CODE -ne 0 ]; then
            echo "::set-output name=publish_failed::true"
          fi

      - name: Check for EOTP and Prompt for New OTP
        if: ${{ steps.lerna-publish.outputs.publish_failed == 'true' && contains(env.OUTPUT, 'HttpErrorAuthOTP') }}
        uses: step-security/wait-for-secrets@v1
        id: wait-for-new-otp
        with:
          secrets: |
            OTP:
              name: 'New OTP to publish package'
              description: 'OTP from authenticator app'

      - name: Retry Lerna Publish with New OTP
        if: ${{ steps.lerna-publish.outputs.publish_failed == 'true' && contains(env.OUTPUT, 'HttpErrorAuthOTP') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          # Retry the publish command with the new OTP
          pnpm run local-lerna publish from-package --force-publish --yes --otp ${{ steps.wait-for-new-otp.outputs.OTP }} || {
            echo "::error title=Publish Failed::Publishing failed even after providing a new OTP."
            exit 1
          }